# Generated by Django 5.0.6 on 2024-05-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(blank=True, max_length=100, null=True)),
                ('CDesc', models.CharField(blank=True, max_length=100, null=True)),
                ('CImage', models.ImageField(blank=True, null=True, upload_to='Category Images')),
            ],
        ),
    ]
