# Generated by Django 5.0.6 on 2024-05-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('PName', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('PDesc', models.CharField(blank=True, max_length=100, null=True)),
                ('PImage', models.ImageField(blank=True, null=True, upload_to='Product Images')),
            ],
        ),
    ]
