# Generated by Django 5.0.6 on 2024-05-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_registrationdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='Confirm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
