# Generated by Django 5.0.6 on 2024-05-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_registrationdb_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UName', models.CharField(blank=True, max_length=100, null=True)),
                ('PName', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('TPrice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
